/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.ImageIcon;

/**
 *
 * @author david
 */
public class HalleyDescription extends javax.swing.JPanel {

    /**
     * Creates new form HalleyDescription
     */
    private Methods method;
    
    public HalleyDescription(Methods method) {
        this.method = method;
        initComponents();
        loadContent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        text1 = new javax.swing.JTextArea();
        nMath = new javax.swing.JLabel();
        nGraph = new javax.swing.JLabel();
        applicationButton = new javax.swing.JButton();

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        titleLabel.setText("Titulo");

        scrollPane.setMaximumSize(new java.awt.Dimension(800, 800));
        scrollPane.setMinimumSize(new java.awt.Dimension(800, 800));
        scrollPane.setPreferredSize(new java.awt.Dimension(800, 800));

        panel.setMaximumSize(new java.awt.Dimension(800, 800));
        panel.setMinimumSize(new java.awt.Dimension(800, 800));
        panel.setName(""); // NOI18N
        panel.setPreferredSize(new java.awt.Dimension(800, 800));

        text1.setEditable(false);
        text1.setColumns(20);
        text1.setRows(5);
        text1.setText("     O método de Halley é usado para busca de raizes de funções reais de uma variável que \npossuem primeira e segunda derivada contínuas, realizando iterativamente uma sequência de\naproximações à raiz, tendo uma taxa de convergência cúbica. Inventado pelo fisíco Edmond \nHalley, o algoritmo consiste em aplicar o método de Newton-Raphson duas vezes. Esse segundo\nmétodo, desenvolvido por Isaac Newton e Joseph Raphson, estima as raízes de uma função\nescolhendo-se uma aproximação inicial; Cria-se então um método iterativo, repetindo o processo\nde cálculo a reta tangente\na partir da darivada da função no ponto e a interseção dela com o eixo das abcissas.");

        nMath.setText("jLabel1");

        nGraph.setText("jLabel2");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(nMath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nGraph)
                .addGap(198, 198, 198))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nMath)
                    .addComponent(nGraph))
                .addContainerGap(540, Short.MAX_VALUE))
        );

        scrollPane.setViewportView(panel);

        applicationButton.setText("Aplicacao");
        applicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 799, Short.MAX_VALUE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(applicationButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(applicationButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void applicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicationButtonActionPerformed
        getParent().add(new Application(method));
        getParent().revalidate();
        getParent().remove(this);
    }//GEN-LAST:event_applicationButtonActionPerformed

    private void loadContent() {
        nMath.setText("");
        nGraph.setText("");
        
        nMath.setIcon(new ImageIcon("..//images//NewtonMath.png"));
        nGraph.setIcon(new ImageIcon("..//images//NewtonGraph.png"));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applicationButton;
    private javax.swing.JLabel nGraph;
    private javax.swing.JLabel nMath;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextArea text1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
